### ISSUE TITLE
-p -a fail

### ISSUE THREAD

**Issue by kendomaniac** [mikessh/oncofuse#4]
Dear Mikhail,
I think you have done a great job creatin Oncofuse.
I am using the latest version of Oncofuse as add on of my chimera Biocinductor package.
I found that if I use a line like this 
java -Xmx1G -jar /Users/raffaelecalogero/Library/R/3.1/library/chimera/oncofuse/Oncofuse.jar of_Sat-Mar-28-08-08-48-2015 coord HEM of.out_Sat-Mar-28-08-08-48-2015 -a hg19 -p 1
the program does not start
if instead I use
java -Xmx1G -jar /Users/raffaelecalogero/Library/R/3.1/library/chimera/oncofuse/Oncofuse.jar of_Sat-Mar-28-08-08-48-2015 coord HEM of.out_Sat-Mar-28-08-08-48-2015
everything works.
Could you please fix this point?
Cheers
Raf

**Comment by mikessh** [comment]
Dear Raf,
Thanks a lot for your feedback! Try executing 
```
java -Xmx1G -jar /Users/raffaelecalogero/Library/R/3.1/library/chimera/oncofuse/Oncofuse.jar -a hg19 -p 1 of_Sat-Mar-28-08-08-48-2015 coord HEM of.out_Sat-Mar-28-08-08-48-2015
```
standard CLI parser for Groovy will not handle options (`-a`, etc) if they are provided after other arguments.

**Comment by kendomaniac** [comment]
Hi Mikhail
Thanks for the quick answer.
I follow you suggestion and it works.
It migth be useful that you highligth the need to a specific order of the parameters in the readme.
Thanks again!
Raf
