### ISSUE TITLE
Support for STAR-Fusion output

### ISSUE THREAD

**Issue by johanneskoester** [mikessh/oncofuse#6]
Hi,
thanks for this interesting tool! I would like to suggest to add support for the output of [STAR-Fusion](https://github.com/STAR-Fusion/STAR-Fusion).
My feeling is that using plain STAR output only will introduce quite some false positives that would be removed by the postprocessiong of STAR-Fusion.

Thanks,
Johannes

**Comment by mikessh** [comment]
Hi Johannes,

I've just added a parser for it, seems to work fine on the example provided there.

Best,
Mike
